### DISCUSSION TITLE
Cache CLI in GitHub Actions?

### DISCUSSION THREAD

**Discussion by jonny-harte** [forcedotcom/cli#2600] [Q&A] [answered]
Hi, does anyone know the best way to cache the sf cli in GitHub Actions? At present is takes about 1 minutes to install the cli and plugins each run and I'd like to reduce this down as much as possible. I tried caching the global node modules but this caused `sf: command not found` on subsequent runs.

Are there additional paths I need to add to make it work or do I need to create a docker image or something else that can be cached in the Actions?

```
- name: Cache
  id: cache
  uses: actions/cache@v3
  with:
    path: |
      ~/.npm
      node_modules
    key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

- name: Setup Node
  if: steps.cache.outputs.cache-hit != 'true'
  uses: actions/setup-node@v4
  with:
    node-version: ">=20"

- name: Install Salesforce CLI & Plugins
  if: steps.cache.outputs.cache-hit != 'true'
  shell: bash
  run: |
    sudo npm install @salesforce/cli --global
    echo y | sf plugins install sfdx-git-delta
    sf --version
    sf plugins --core

- name: Install Dependencies
  if: steps.cache.outputs.cache-hit != 'true'
  shell: bash
  run: npm ci
```

**Comment by mshanemc** [comment]
`npm install -g` will also add the package's bin to your path, which I think is what you're missing.

note also `--omit=dev` which will only install the production dependencies and may make life faster

**Reply by jonny-harte** [reply]
I added `/usr/local/bin/sf` to the cache path but still the same error. Any other directories I should add?

```
- name: Cache
      id: cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          /usr/local/bin/sf
        key: Salesforce-CLI
```
