### ISSUE TITLE
Deploying no longer reports progress

### ISSUE THREAD

**Issue by AndrewRayCode** [forcedotcom/cli#1126]
docker image `salesforce/salesforcedx:7.113.0-slim`

```
SFDX_USE_PROGRESS_BAR=false timeout 120m sfdx force:source:deploy --wait 122 -u Sandbox --testlevel RunLocalTests -x manifest/package.xml --checkonly
*** Deploying with SOAP API ***
Deploy ID: MYID

=== Status: Pending

No components deployed
```

Only `=== Status: Pending` is written out, even though the test run goes on in the sandbox.

Then our CI system kills it with:

> Too long with no output (exceeded 10m0s): context deadline exceeded

@mshanemc why is this behavior

**Comment by MuriloKakazu** [comment]
I had this same problem some releases ago... And since you seem to also have CircleCI, you can just set the `no_output_timeout` on your deployment step to avoid the job being canceled:

```
- run:
      name: Deploy to QA
      command: |
          timeout 90m sfdx force:source:deploy --targetusername qa --wait 92 --testlevel RunLocalTests --sourcepath ./src
      no_output_timeout: 92m
```
The above was the best solution I could find... Otherwise you will have to re-enable the status bar so the deployment progress is presented to STDOUT, and thus CircleCI won't cancel the job.... although the CLI will still present nothing to STDOUT on other machines if there's already another deployment running on that org... :P
