### ISSUE TITLE
No TOKEN named cardColorBorder found

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#1197]
### Summary

I had to declare some of the values from the `slds-card` class because when I added my card inside the standard tab component, the borders of the card were gone.

![image](https://user-images.githubusercontent.com/55927613/134514645-6c7fa70b-9a2d-4751-aae8-7f920f574ef8.png)

But when I try to deploy this component I get this error.

### Steps To Reproduce:

1 - create a lwc
2 - create a .css file and add this class there

````css
.my-card {
    width: 400px;
    color: var(--simple-text-color, #aaaaaa);
    position: relative;
    padding: var(--lwc-spacingSmall, 0.75rem);
    border-width: var(--lwc-borderWidthThin, 1px);
    border-style: solid;
    border-color: var(--lwc-cardColorBorder,rgb(221, 219, 218));
    border-radius: var(--lwc-borderRadiusMedium, 0.25rem);
    background-clip: padding-box;
    box-shadow: var(--lwc-cardShadow,0 2px 2px 0 rgba(0, 0, 0, 0.10));
}
````
3 - add the my-card class somewhere in your .html
4 - try to deploy the component and verify you get the same error message
5 - change my-card to slds-card
6 - deploy your component and verify it is deployed with no problem
7 - place your component somehwere in a lightning page. 
8 - inspect the page and verify that these tokens are present on the Sandbox

![image](https://user-images.githubusercontent.com/55927613/134515372-dbd4b023-d14d-4e24-bb3e-4970475506f8.png)

### Expected result

If slds-card uses --lwc-cardColorBorder token, and it is present on a Sandbox, it is expected that I can deploy a component that uses it.

### Actual result

Can't deploy a component that uses --lwc-cardColorBorder css token

### System Information

![image](https://user-images.githubusercontent.com/55927613/134515620-e1e53f34-0843-490a-9443-cd618eb33eb1.png)

### Additional information

I had to copy the slds-card css because of this SLDS bug which removes the borders when the component is inside the Standard Tabs component

![image](https://user-images.githubusercontent.com/55927613/134515783-fa90b02b-ca79-4c1d-ad1a-a15482ce3b1c.png)

**Comment by AllanOricil** [comment]
I noticed that some --lwc--cardSOMETHING tokens are present on sandboxes and I could not find the --lwc-cardColorBorder token. Maybe it is a regression from the production code that removed this token?

**Comment by mshanemc** [comment]
I'm asking some LWC folks who might know.  That doesn't look like a CLI error.

**Comment by AllanOricil** [comment]
> I'm asking some LWC folks who might know. That doesn't look like a CLI error.

@mshanemc thank you. I just did not know where exactly to reportu this issue. So I decided to open it here because someone else could have the same issue while using sfdx. 

I also opened on the SLDS repo, because they control the CSS Variables. 

But it is better to report to the responsible for the Salesforce application. The one that runs on every environment. Because the token should exist, as it is used by a class called "slds-card". When you inspect the Stylesheets loaded on the app you can see that this token is not present, but it is used by slds-card. And because of that if we try to use it on a LWC, it throws an exception while deploying.

**Comment by mshanemc** [comment]
Some observations regarding the issue:
1. can you try on an up-to-date CLI
2. the styling hooks  don’t match the ones that are [documented for Cards](https://www.lightningdesignsystem.com/components/cards/#Styling-Hooks-Overview) (prefix, name and case are invalid)
3. can you explain step 5 more
4. are your orgs on the same release? (prod vs pre-release sandbox).  This may be a release boundary change

**Comment by AllanOricil** [comment]
@mshanemc steps with more details


### Steps To Reproduce:

1 - create a lwc with this template. The .js does not need to have anything.

````html
<template>
<div class="my-card" style="width: 300px;"></div>
</template>
````
2 - create a .css for your component and paste this

````css
:host {
    --simple-text-color: #aaaaaa;
    --strong-text-color: #585858;
}

.my-card {
    width: 400px;
    color: var(--simple-text-color, #aaaaaa);
    position: relative;
    padding: var(--lwc-spacingSmall, 0.75rem);
    border-width: var(--lwc-borderWidthThin, 1px);
    border-style: solid;
    border-color: var(--lwc-cardColorBorder,rgb(221, 219, 218));
    border-radius: var(--lwc-borderRadiusMedium, 0.25rem);
    background-clip: padding-box;
    box-shadow: var(--lwc-cardShadow,0 2px 2px 0 rgba(0, 0, 0, 0.10));
}
````

3 - try to deploy the component and verify you get the same error message. 
4 - Now change `my-card` to `slds-card` on your template. Like this:

````html
<template>
<div class="slds-card" style="width: 300px;"></div>
</template>
````

5 - deploy your component again and verify it is deployed with no problem.
6 - place your component somehwere in a lightning page. 
7 - inspect the page and verify that these tokens the API is complaining about do exist in the Sandbox, as shown image below:

![image](https://user-images.githubusercontent.com/55927613/134515372-dbd4b023-d14d-4e24-bb3e-4970475506f8.png)

If you hover over the token that is referenced on the `slds-card`, you will see that it is undefined. It seems that on my sandbox,  both `--slds-c-card-color-border` and `--lwc-cardColorBorder` are undefined.

OBS: The token Name is not wrong. I know that because I copied it from the standard SLDS CSS class called `slds-card`, and also because Im using another token called `--lwc-progressBarColorBackgroundFill`, wich has the same format, and this one works without a problem.
