### ISSUE TITLE
SFDX CLI - multiple sfdx force:mdapi:deploy commands competing for the same folder/file? 

### ISSUE THREAD

**Issue by neowit** [forcedotcom/cli#1299]
### Summary

Multiple `sfdx force:mdapi:deploy` commands executed in parallel from the same MDAPI folder but to different Orgs conflict with each other

This issue manifests itself in all sfdx cli versions starting 7.82.0 (did not test in earlier versions) and up to (and including) current. 

### Description:

As part of CI deployment the same PR needs to be validated against several salesforce orgs.
To do that a CI script has the following (not exact copy, but to give an idea)

```
SF_DEPLOYMENT_DIR="/some/path/here" # same deploydir is re-used for all orgs in deployment

# org 1
sfdx force:mdapi:deploy --checkonly --json --targetusername deploymentuser@org1.com \
            --deploydir "$SF_DEPLOYMENT_DIR" --testlevel $TEST_LEVEL --runtests "$TESTS_TO_RUN1" & # run in background, async

#org 2
sfdx force:mdapi:deploy --checkonly --json --targetusername deploymentuser@org2.com \
            --deploydir "$SF_DEPLOYMENT_DIR" --testlevel $TEST_LEVEL --runtests "$TESTS_TO_RUN2" & # run in background, async

#org 3	
sfdx force:mdapi:deploy --checkonly --json --targetusername deploymentuser@org3.com \
            --deploydir "$SF_DEPLOYMENT_DIR" --testlevel $TEST_LEVEL --runtests "$TESTS_TO_RUN3" & # run in background, async
```			
			
The issue is - if commands for `org 2` or `org 3` are executed just like it is above (i.e. at the same time) then most of the time at least 1 (more often 2) deployments fails with either `UNKNOWN_ERROR` or `'package.xml' missing` error, or some other error related to incomplete metadata folder/file structure
It looks as if each subsequent `sfdx force:mdapi:deploy` has a clash (at file system level) with preceding `sfdx force:mdapi:deploy`

If we add a `sleep 120` after each deployment, i.e. give each  `sfdx force:mdapi:deploy` command some time to start in isolation, then the whole thing almost never fails.

This version works (but adds undesirable pause):

```
SF_DEPLOYMENT_DIR="/some/path/here" # same deploydir is re-used for all orgs in deployment

# org 1
sfdx force:mdapi:deploy --checkonly --json --targetusername deploymentuser@org1.com \
            --deploydir "$SF_DEPLOYMENT_DIR" --testlevel $TEST_LEVEL --runtests "$TESTS_TO_RUN1"  & # run in background, async
sleep 120

#org2
sfdx force:mdapi:deploy --checkonly --json --targetusername deploymentuser@org2.com \
            --deploydir "$SF_DEPLOYMENT_DIR" --testlevel $TEST_LEVEL --runtests "$TESTS_TO_RUN2"  & # run in background, async
sleep 120

#org3	
sfdx force:mdapi:deploy --checkonly --json --targetusername deploymentuser@org.com \
            --deploydir "$SF_DEPLOYMENT_DIR" --testlevel $TEST_LEVEL --runtests "$TESTS_TO_RUN3"  & # run in background, async
sleep 120 # not sure if this one make any difference, but that's what currently working
```

The problem is - PR validation is done many times each day by many developers and `(N-1) x 2`  additional minutes (where N is number of orgs in each validation) spent to start deployments in every PR validation quickly adds up.

**Question** - what can be done to stop multiple `sfdx force:mdapi:deploy` executed **in parallel** from conflicting with each other?
Thank you

PS: this problem looks like it is caused because some (writeable) file system resource is being re-used when multiple `sfdx force:mdapi:deploy` are executed on the same machine at the same time. If each `sfdx force:mdapi:deploy` was truly resource independent (for stuff it writes) then this would probably solve this `clash` issue

**Comment by AllanOricil** [comment]
@neowit Instead of having one job doing N org validations, make N jobs, each with its own copy of the repo, to run a validation. This way you won't need to repeat/write the sfdx command N times. It also follows a DRY implementation and your job will be reusable.

**Comment by neowit** [comment]
Hello @AllanOricil 
Thank you for the suggestion. 
As I wrote in my message - the above is an example to give an idea. N is not a fixed number and there is no repetition in the real CI script. Each deployment is indeed its own job which re-use metadata prepared by preceding stages of deployment.
Those 3 `sfdx force:mdapi:deploy` lines in my example are just a simplified way to illustrate what's going on.
Having to prepare N versions of same `SF_DEPLOYMENT_DIR` with identical content does not feel like a DRY implementation.

**Comment by AllanOricil** [comment]
You said that the problem happens if you reuse the same folder to run the validation command. If you are indeed using different jobs, how is it possible you are still facing this problem?
You are probably not checking out the repo again in every job. Every job should work with its own copy of the repo. Build a job that can be reused, like a function. Then you spawn multiple instances of this job to avoid repeating sfdx commands several times.

This is an example of implementation I did using Github Actions for a customer that works well:

````yml
name: Validation Workflow

on:
    pull_request:
        types: [opened, synchronize, ready_for_review]
        branches:
            - main

    workflow_dispatch:

jobs:

    validate-vlocdevbas:
        uses: VodafoneIS/sf-metadata/.github/workflows/validation.yml@main
        with:
            ENVIRONMENT: vlocdevbas
        secrets:
            SF_ORG_ALIAS: ${{ secrets.SF_ORG_ALIAS }}
            SF_INSTANCE_URL: ${{ secrets.SF_INSTANCE_URL }}
            SF_SFDX_AUTH_URL: ${{ secrets.SF_SFDX_AUTH_URL }}
            TAG_NAME: ${{ secrets.TAG_NAME }}
    
    validate-vlocdevpro:
        uses: VodafoneIS/sf-metadata/.github/workflows/validation.yml@main
        with:
            ENVIRONMENT: vlocdevpro
        secrets:
            SF_ORG_ALIAS: ${{ secrets.SF_ORG_ALIAS }}
            SF_INSTANCE_URL: ${{ secrets.SF_INSTANCE_URL }}
            SF_SFDX_AUTH_URL: ${{ secrets.SF_SFDX_AUTH_URL }}
            TAG_NAME: ${{ secrets.TAG_NAME }}
````

In this implementation I have used a feature called "Reusable Workflow" that was created based on DRY implementations. Instead of repeating a sequence of jobs multiple times, I separate them in diferent templates, like functions, and then I reuse them. This way I can avoid repeating cli commands. 
Each validation workflow does the following:

- check out the repo. This way each validation works with its own copy of the repo and this error you mentioned won't happen.
- authenticate to an org
- compute metadata diff using sgd plugin
- run sfdx validation command. If it failed exit with 1.
- compute code coverage. If code coverage is below MIN_COVERAGE(default 75) exit with 1.
