### ISSUE TITLE
'sf project deploy start' commands are taking a long time to pass back a completion status to pipelines

### ISSUE THREAD

**Issue by stuartgrieve** [forcedotcom/cli#2495]
### Summary
We run our deployment automation using Bitbucket Pipelines, using the docker image: salesforce/cli:nightly-full

Over the past week or two, our development team has noticed validations/deployments hitting the sandbox, completing, and then a significant wait before the `sf project deploy start` command completes in Bitbucket.

After some further investigations, it seems to happen more so on successful runs. I ran four scenarios which run on a consistent pipeline script to a single sandbox:

* branch1 (contains valid metadata so was passing): triggered a build, org showed it passed, the CLI outputs `Status: Succeeded`
![branchA](https://github.com/forcedotcom/cli/assets/50016580/cd806180-b3ce-4253-97e1-cd772c9d8682)
![Screenshot 2023-09-28 at 08 57 55](https://github.com/forcedotcom/cli/assets/50016580/03324559-28ca-4872-ad03-084fea6f2357)
![branchA-1](https://github.com/forcedotcom/cli/assets/50016580/b96e8314-dd32-4eb7-8731-8084a8e63de6)
Some 20 minutes later, Bitbucket has still not received the completion status
![branchA-2](https://github.com/forcedotcom/cli/assets/50016580/7e894b9d-1e09-4757-8c55-996e3b3be027)
* branch2 (contains failing tests): triggered a build, org showed it failed, within a minute the step in Bitbucket displays the failure
* branch1 (untouched from the first build): triggered again, same outcome, it passes, but the status hangs
* branch1 (modified a class to break the validation): as with branch2, org presented the failure and almost immediately the Bitbucket step failed too
![Screenshot 2023-09-28 at 09 20 29](https://github.com/forcedotcom/cli/assets/50016580/1a38f133-fec4-4bd6-b9bc-71e9fa8d5412)

### Steps To Reproduce

I can't provide our repository since the content is sensitive, but this behaviour seems to be agnostic to the metadata included in the build anyway. Below is the script we're using for PR validations:

```yaml
# Author: Slalom

# Docker image to be used
image: 
  name: salesforce/cli:nightly-full
  run-as-user: 0

# Maximum minutes a step can execute before timing out
options:
  max-time: 120

pipelines:

  pull-requests:

    feature/*:
      - step:
          name: QA Sandbox Validation
          script:
            - sf version --verbose --json
            - echo y | sfdx plugins:install sfdx-git-delta
            - export COMMIT_MESSAGE=$(git log --format=%B -n 1 $BITBUCKET_COMMIT)
            - if [[ "$COMMIT_MESSAGE" == *"[bypass-delta]"* ]]; then echo Bypassing creation of delta directory; else mkdir delta-deployment; echo 'force-app/main/default/layouts/*' > .deltainclude; sfdx sgd:source:delta --to origin/$BITBUCKET_BRANCH --from origin/$BITBUCKET_PR_DESTINATION_BRANCH --output "delta-deployment" --generate-delta --include .deltainclude; echo Delta directory result...; ls -R delta-deployment; fi;
            - export TEST_FILES=$(python3 scripts/get-test-class-list.py delta-deployment/force-app/main/default/classes delta-deployment/force-app/main/default/triggers | tr ',' ' '); echo $TEST_FILES
            - export CLIENT_ID=$PLATFORM_QA_SECRET; export USERNAME=$PLATFORM_QA_USERNAME; export URL=$PLATFORM_QA_URL;
            - openssl enc -nosalt -aes-256-cbc -d -in certificates/server.key.enc -out certificates/server.key -base64 -K $ENCRYPTION_KEY -iv $ENCRYPTION_IV; ls certificates
            - sf login org jwt --client-id $CLIENT_ID --username $USERNAME -f certificates/server.key --instance-url $URL
            - if [ "$(ls -A delta-deployment/force-app/main/default)" ] || [ "$(ls -A delta-deployment/omniStudio-metadata)" ] || [ "$(ls -A delta-deployment/unpackaged-metadata)" ]; then sf project deploy start --verbose --ignore-conflicts --ignore-warnings --source-dir delta-deployment --dry-run --test-level RunSpecifiedTests --tests $TEST_FILES "Test With Space" --target-org $USERNAME --wait 60; else echo "No delta detected, full validation..."; sf project deploy start --verbose --ignore-conflicts --ignore-warnings --source-dir force-app/main/default omniStudio-metadata unpackaged-metadata --dry-run --test-level RunLocalTests --target-org $USERNAME --wait 60; fi
            - sf logout org --target-org $USERNAME --no-prompt
```

### Expected result
When a validation/deployment successfully completes in an org, the CLI receives the exit code shortly afterwards

### Actual result
Instead, we are seeing it hang for 10-20 minutes.

### System Information
Terminal: bash

```json
{
  "cliVersion": "@salesforce/cli/2.12.0",
  "architecture": "linux-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Linux 5.15.0-1043-aws",
  "shell": "bash",
  "rootPath": "/usr/local/lib/nodejs/lib/node_modules/@salesforce/cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.8 (core)",
    "@oclif/plugin-commands 2.2.26 (core)",
    "@oclif/plugin-help 5.2.19 (core)",
    "@oclif/plugin-not-found 2.4.1 (core)",
    "@oclif/plugin-plugins 3.8.2 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.2.3 (core)",
    "@oclif/plugin-version 1.3.10 (core)",
    "@oclif/plugin-warn-if-update-available 2.1.0 (core)",
    "@oclif/plugin-which 2.2.32 (core)",
    "@salesforce/cli 2.12.0 (core)",
    "apex 2.3.15 (core)",
    "auth 2.8.17 (core)",
    "data 2.5.12 (core)",
    "deploy-retrieve 1.18.2 (core)",
    "info 2.6.45 (core)",
    "limits 2.3.35 (core)",
    "login 1.2.31 (core)",
    "marketplace 0.2.2 (core)",
    "org 2.10.8 (core)",
    "schema 2.3.28 (core)",
    "settings 1.4.30 (core)",
    "sobject 0.2.7 (core)",
    "source 2.10.36 (core)",
    "telemetry 2.3.4 (core)",
    "templates 55.5.13 (core)",
    "trust 2.6.15 (core)",
    "user 2.3.32 (core)"
  ]
}
```
