### ISSUE TITLE
sfdx force:package:installed:list crashing: ModuleLoadError: [MODULE_NOT_FOUND] import() failed to load 

### ISSUE THREAD

**Issue by nvuillam** [forcedotcom/cli#3000]
### Summary

Command sfdx force:package:installed:list is crashing since plugin-packaging@2.8.2

### Expected result
The list of packages :)

### Actual result
Crash

```sh
sfdx force:package:installed:list -u deploy.github@*****.com.recette --json

 ›   ModuleLoadError: [MODULE_NOT_FOUND] import() failed to load 
 ›   /home/ubuntu/.local/share/sf/node_modules/@salesforce/plugin-packaging/lib
 ›   /commands/package/installed/list.js: Cannot find package 
 ›   '/home/ubuntu/.local/share/sf/node_modules/terminal-link/node_modules/ansi
 ›   -escapes/package.json' imported from 
 ›   /home/ubuntu/.local/share/sf/node_modules/terminal-link/index.js
 ›   Did you mean to import ansi-escapes/index.js?
 ›   Code: MODULE_NOT_FOUND

```

### System Information
GitHub Actions runner (ubuntu)

```json
{
  "architecture": "linux-x64",
  "cliVersion": "@salesforce/cli/2.56.7",
  "nodeVersion": "node-v20.11.0",
  "osVersion": "Linux 5.15.0-116-generic",
  "rootPath": "/home/ubuntu/actions-runner-3/_work/_tool/node/20.11.0/x64/lib/node_modules/@salesforce/cli",
  "shell": "bash",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.0 (core)",
    "@oclif/plugin-commands 4.0.11 (core)",
    "@oclif/plugin-help 6.2.8 (core)",
    "@oclif/plugin-not-found 3.2.16 (core)",
    "@oclif/plugin-plugins 5.4.4 (core)",
    "@oclif/plugin-search 1.2.5 (core)",
    "@oclif/plugin-update 4.5.3 (core)",
    "@oclif/plugin-version 2.2.10 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.11 (core)",
    "@oclif/plugin-which 3.2.10 (core)",
    "@salesforce/cli 2.56.7 (core)",
    "apex 3.4.2 (core)",
    "api 1.1.0 (core)",
    "auth 3.6.48 (core)",
    "data 3.6.1 (core)",
    "deploy-retrieve 3.10.1 (core)",
    "info 3.3.29 (core)",
    "limits 3.3.25 (core)",
    "marketplace 1.2.22 (core)",
    "org 4.5.4 (core)",
    "packaging 2.8.2 (user) published 2 days ago (Sat Aug 31 2024)",
    "schema 3.3.24 (core)",
    "settings 2.3.13 (core)",
    "sobject 1.4.29 (core)",
    "source 3.5.14 (core)",
    "telemetry 3.6.7 (core)",
    "templates 56.3.12 (core)",
    "trust 3.7.23 (core)",
    "user 3.5.25 (core)",
    "sfdx-essentials 2.12.0 (user) published 992 days ago (Tue Dec 14 2021)",
    "sfdx-git-delta 5.[42](https://github.com/Groupe-Sun-R/crm-salesforce/actions/runs/10668673318/job/29569595187#step:4:43).1 (user) published 7 days ago (Mon Aug 26 2024)",
    "sfdx-hardis 4.53.0 (user) published 13 days ago (Tue Aug 20 2024)"
  ]
}
```

**Comment by cristiand391** [comment]
I'm not able to repro this locally, tested by installing sf 2.56.7 via npm **and** tarballs, then `sf plugins install @salesforce/plugin-packaging@2.8.2`:

tarball: 
```
➜  sdr git:(sh/deploy-zip-size) ~/cli/sf/bin/sf force:package:installed:list -o 1gp
 ›   Warning: Plugin @salesforce/plugin-packaging (2.8.2) differs from the version specified by sf (2.8.0)
Warning: The "force package installed list" command has been deprecated. Use "package installed list" instead.
 ID Package ID Package Name Namespace Package Version ID Version Name Version
 ── ────────── ──────────── ───────── ────────────────── ──────────── ───────
```

npm install:
```
➜  plugin-packaging git:(main) sf force:package:installed:list -o 1gp
 ›   Warning: Plugin @salesforce/plugin-packaging (2.8.2) differs from the version specified by sf (2.8.0)
Warning: The "force package installed list" command has been deprecated. Use "package installed list" instead.
 ID Package ID Package Name Namespace Package Version ID Version Name Version
 ── ────────── ──────────── ───────── ────────────────── ──────────── ───────
```

can you share how are you installing plugin-packaging? 
fwiw, it's not necessary to install it manually unless you want to try some latest feature (we have a CLI nightly channel for that).

**Comment by nvuillam** [comment]
@cristiand391 

Here is the part with installations

```yaml
          npm install @salesforce/cli --global
          sf plugins install @salesforce/plugin-packaging
          echo 'y' | sfdx plugins:install sfdx-hardis
          echo 'y' | sfdx plugins:install sfdx-essentials
          # echo 'y' | sfdx plugins:install sfdmu # Disabled while it does not play well with @salesforce/cli
          echo 'y' | sfdx plugins:install sfdx-git-delta
            sf version --verbose --json
```

Below is the full GitHub Actions workflow

```yaml
# Manual updates in in job step "Login & Process Deployment" below:
# - variables for additional branches: add SFDX_CLIENT_ID / KEY variables
# - To use slack notifications, you can also define SLACK_TOKEN and SLACK_CHANNEL_ID
#   - For branch scoped messages, add SLACK_CHANNEL_ID_ + branch name (ex: SLACK_CHANNEL_ID_INTEGRATION, SLACK_CHANNEL_ID_UAT)
on:
  push:
    # Add your major branches names here
    branches:
      - main
      - preprod
      - recette
      - integration

name: Process Deployment (sfdx-hardis)
permissions: read-all
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  process_deployment:
    name: Process Deployment to Major Org
    runs-on: [self-hosted, linux]
    steps:
      # Git Checkout
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      # Setup node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      # SFDX & plugins
      - name: Install SFDX and plugins
        run: |
          npm install @salesforce/cli --global
          sf plugins install @salesforce/plugin-packaging
          echo 'y' | sfdx plugins:install sfdx-hardis
          echo 'y' | sfdx plugins:install sfdx-essentials
          # echo 'y' | sfdx plugins:install sfdmu # Disabled while it does not play well with @salesforce/cli
          echo 'y' | sfdx plugins:install sfdx-git-delta
            sf version --verbose --json
      # Set env branch variable (github.ref_name seems to not work)
      - name: Set env.BRANCH
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
      # Login & check deploy with test classes & code coverage
      - name: Login & Process Deployment
        env:
          SFDX_CLIENT_ID_INTEGRATION: ${{ secrets.SFDX_CLIENT_ID_INTEGRATION}}
          SFDX_CLIENT_KEY_INTEGRATION: ${{ secrets.SFDX_CLIENT_KEY_INTEGRATION}}
          SFDX_CLIENT_ID_RECETTE: ${{ secrets.SFDX_CLIENT_ID_RECETTE}}
          SFDX_CLIENT_KEY_RECETTE: ${{ secrets.SFDX_CLIENT_KEY_RECETTE}}
          SFDX_CLIENT_ID_PREPROD: ${{ secrets.SFDX_CLIENT_ID_PREPROD}}
          SFDX_CLIENT_KEY_PREPROD: ${{ secrets.SFDX_CLIENT_KEY_PREPROD}}
          SFDX_CLIENT_ID_MAIN: ${{ secrets.SFDX_CLIENT_ID_MAIN}}
          SFDX_CLIENT_KEY_MAIN: ${{ secrets.SFDX_CLIENT_KEY_MAIN}}
          SFDX_DEPLOY_WAIT_MINUTES: 120 # Override if necessary
          SFDX_TEST_WAIT_MINUTES: 120 # Override if necessary
          CI_COMMIT_REF_NAME: ${{ env.BRANCH }} # Defines the target branch of the PR
          ORG_ALIAS: ${{ env.BRANCH }} # Defines the target branch of the PR
          CONFIG_BRANCH: ${{ env.BRANCH }} # Defines the target branch of the PR
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          MS_TEAMS_WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          JIRA_HOST : ${{ secrets.JIRA_HOST }}
          JIRA_PAT: ${{ secrets.JIRA_PAT }}
          JIRA_TICKET_REGEX: (CLDVOLT01-[0-9]+)
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FORCE_COLOR: "1"
        run: |
          echo "Process SFDX deployment using Hardis against \"$CONFIG_BRANCH\""
          sfdx hardis:auth:login
          sfdx hardis:project:deploy:sources:dx
```
