### ISSUE TITLE
sf agent generate agent-spec always produces empty topics array regardless of configuration

### ISSUE THREAD

**Issue by hangingman** [forcedotcom/cli#3302]
### Summary
The `sf agent generate agent-spec` command consistently fails to generate topics, resulting in `topics: []` in the output YAML file, regardless of agent properties provided. This occurs even with simple, standard agent configurations and affects both interactive and flag-based command execution.

### Steps To Reproduce

**Environment Setup:**
1. Create SFDX project with `sf project generate --name agentforce-test`
2. Authenticate to Developer Edition org with Einstein/Agentforce enabled
3. Ensure CLI is updated to latest version

```shell
✗ sf version
@salesforce/cli/2.89.8 darwin-x64 node-v23.11.1
```

**Reproduction Steps:**

**Test 1: Basic Interactive Execution**
```bash
sf agent generate agent-spec --target-org DevOrg
```
Interactive inputs:
- Type of agent: `internal`
- Company name: `Test Company`
- Company description: `Salesforce consulting company`
- Role of agent: `Customer support agent`

result
```yaml
agentType: internal
companyName: Test Company
companyDescription: Salesforce consulting company
role: Customer support agent
maxNumOfTopics: 5
enrichLogs: false
tone: casual
topics: []
```

**Test 2: Flag-based Execution (Simple)**
```bash
sf agent generate agent-spec --type internal \
  --company-name "Test Company" \
  --company-description "Salesforce consulting company" \
  --role "Customer support agent" \
  --max-topics 1 --tone formal \
  --target-org DevOrg
```

result
```yaml
agentType: internal
companyName: Test Company
companyDescription: Salesforce consulting company
role: Customer support agent
maxNumOfTopics: 1
enrichLogs: false
tone: formal
topics: []
```

### Expected result
According to the documentation at https://developer.salesforce.com/docs/einstein/genai/guide/agent-dx-generate-agent-spec.html:

> The spec file also contains an LLM-generated list of topics based on this information... The bottom part contains the LLM-generated list of topics.

The generated `specs/agentSpec.yaml` should contain topics like:
```yaml
topics:
  - name: Guest Check-In Automation
    description: Streamline the guest check-in process using AI.
  - name: Personalized Guest Services
    description: Provide tailored recommendations and services.
  - name: Predictive Maintenance
    description: Use AI to forecast and prevent equipment failures.
```

### Actual result
All executions consistently produce the same result with empty topics:

Generated file content:
```yaml
agentType: internal
companyName: Test Company
companyDescription: Salesforce consulting company
role: Customer support agent
maxNumOfTopics: 1
enrichLogs: false
tone: formal
topics: []  # ← Always empty regardless of configuration
```

### Additional information

**Plugin Version Warning:**
Every execution shows:
```
Warning: Plugin @salesforce/plugin-agent (1.22.2) differs from the version specified by sf (1.21.1)
```

**Attempted Variations:**
- Different `--max-topics` values (1, 2, 3)
- Various agent types and descriptions
- Both new spec creation and existing spec refinement

**Consistent Behavior:**
- Command completes without errors
- All agent properties are correctly saved
- Only `topics: []` array remains consistently empty
- Issue persists across multiple days and CLI sessions

### System Information
**Shell:** zsh
**Platform:** macOS

```json
✗ sf version --verbose --json
{
  "architecture": "darwin-x64",
  "cliVersion": "@salesforce/cli/2.89.8",
  "nodeVersion": "node-v23.11.1",
  "osVersion": "Darwin 22.6.0",
  "rootPath": "/usr/local/Cellar/sf/2.89.8/libexec/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.28 (core)",
    "@oclif/plugin-commands 4.1.25 (core)",
    "@oclif/plugin-help 6.2.28 (core)",
    "@oclif/plugin-not-found 3.2.51 (core)",
    "@oclif/plugin-plugins 5.4.37 (core)",
    "@oclif/plugin-search 1.2.24 (core)",
    "@oclif/plugin-update 4.6.39 (core)",
    "@oclif/plugin-version 2.2.28 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.39 (core)",
    "@oclif/plugin-which 3.2.35 (core)",
    "@salesforce/cli 2.89.8 (core)",
    "agent 1.22.2 (user) published 6 days ago (Wed May 21 2025)",
    "apex 3.6.17 (core)",
    "api 1.3.3 (core)",
    "auth 3.6.120 (core)",
    "data 4.0.32 (core)",
    "deploy-retrieve 3.22.10 (core)",
    "info 3.4.60 (core)",
    "limits 3.3.54 (core)",
    "marketplace 1.3.8 (core)",
    "org 5.7.8 (core)",
    "packaging 2.13.3 (core)",
    "schema 3.3.62 (core)",
    "settings 2.4.27 (core)",
    "sobject 1.4.56 (core)",
    "telemetry 3.6.41 (core)",
    "templates 56.3.47 (core)",
    "trust 3.7.89 (core)",
    "user 3.6.21 (core)"
  ]
}
```

**Development Org Configuration:**
- Type: Developer Edition
- Einstein: Enabled
- Agentforce: Enabled  
- Data Cloud: Created and active

**Impact:**
This issue blocks the entire Agentforce CLI workflow as the subsequent `sf agent create` command fails with "No topics are associated with agent. Skip saving." when attempting to create an agent from the spec file.

**Comment by shetzel** [comment]
Thank you for the thorough issue report.  Unfortunately, using the same plugin version and the exact repro steps I don't see the same behavior.  My agent spec has this content:

```
agentType: internal
companyName: Test Company
companyDescription: Salesforce consulting company
role: Customer support agent
maxNumOfTopics: 5
enrichLogs: false
tone: casual
topics:
  - name: Customer Issue Resolution
    description: Assist in resolving customer issues using Salesforce.
  - name: Knowledge Base Management
    description: Update and maintain the internal knowledge base.
  - name: Case Routing Optimization
    description: Automate case routing for efficient resolution.
  - name: Customer Interaction History
    description: Track and analyze customer interactions.
  - name: Performance Metrics Reporting
    description: Generate reports on support team performance.
```

I suspect that something might not be configured in the org or with user permissions.  Typically, that would result in an error reported by the server side API that the CLI is calling.  Are you able to create an agent with generated topics using the org UI in that same org?  If you use the above as your agent spec are you able to create an agent in the org (or preview agent creation) using the CLI command?  If you append `--dev-debug` there could be some debug output that provides a clue as well.
