### ISSUE TITLE
ERROR running force:org:create:  The package ancestor for the package version was not found. Ancestor package ID: 05ixxxxxxxxxxxxxx.: Requested Package2 Ancestor IDs

### ISSUE THREAD

**Issue by sjurgis** [forcedotcom/cli#997]
### Summary

This just started happening in CI only and after adding `"ancestorVersion": "0.10.0.1"`

### Steps To Reproduce:

Unclear, but here's sfdx-project.json
```
{
    "packageDirectories": [
        {
            "path": "force-app/main/lib"
        },
        {
            "path": "force-app/main/schema"
        },
        {
            "path": "force-app/main/default",
            "default": true
        },
        {
            "path": "force-app/main/consumers"
        },
        {
            "path": "force-app/main/ui"
        },
        {
            "path": "force-app/main/misc"
        },
        {
            "path": "unpackaged"
        },
        {
            "path": "force-app",
            "package": "fbm-beta",
            "versionName": "ver 1.0",
            "versionNumber": "1.0.0.NEXT",
            "default": false
        },
        {
            "path": "force-app",
            "package": "officialName",
            "versionName": "Version 1.0",
            "versionNumber": "1.0.0.NEXT",
            "postInstallScript": "PostInstallScript",
            "default": false,
            "ancestorVersion": "0.10.0.1"
        }
    ],
    "namespace": "fbm",
    "sfdcLoginUrl": "https://login.salesforce.com",
    "sourceApiVersion": "51.0",
    "packageAliases": {
        "fbm-beta": "0Hoxxxxxxxxxxxxx",
        "fbm-beta@0.1.0-1": "04txxxxxxxxxxxxx,
        <few of these>
        "fbm-beta@0.1.0-10": "04txxxxxxxxxxxxx,
        "officialName": "0Hoxxxxxxxxxxxxx",
        "officialName@0.9.0-1": "04txxxxxxxxxxxxx",
        "officialName@0.9.0-2": "04txxxxxxxxxxxxx",
        <few of these>
        "officialName@0.9.0-3": "04txxxxxxxxxxxxx",
        "officialName@0.9.0-4": "04txxxxxxxxxxxxx",
        "fbm-beta@0.1.0-13": "04txxxxxxxxxxxxx",
        "fbm-beta@0.1.0-14": "04txxxxxxxxxxxxx",
        "officialName@0.10.0-1": "04txxxxxxxxxxxxx"
    }
}

```

Bog standard pipeline

```
name: Apex unit tests
on:
    push:
        paths-ignore:
            - 'force-app/main/ui/**'
            - 'ci'
            - 'scripts'
        branches-ignore:
            - 'master'
jobs:
    apex-test:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - name: Set environment variables
              run: |
                  echo "SFDX_IMPROVED_CODE_COVERAGE=true" >> $GITHUB_ENV
                  echo "SFDX_DISABLE_SOURCE_MEMBER_POLLING=true" >> $GITHUB_ENV
            - name: Checkout
              uses: actions/checkout@v1
            - name: Install sfdx
              uses: sfdx-actions/setup-sfdx@v1
            - name: Create org
              run: echo "${{secrets.DEVHUB_CI_CERT_2021_PRIVATEKEY}}" | ./scripts/create-org.sh "${{secrets.DEVHUB_CI_CERT_2021_CONSUMERKEY}}"
            - name: Push source
              run: sfdx force:source:push
            - name: Run apex tests
              run: sfdx force:apex:test:run -r tap --codecoverage --wait 45
            - name: Enforce apex unit test failed if lower than 76%
              run: ./scripts/check-coverage.sh
            - name: Delete org
              if: always()
              run: sfdx force:org:delete -p

```

Not an issue when running local.
